/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DashboardWalletCallbackRouteImport } from './routes/dashboard/wallet-callback'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard/reviews'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardPaymentCallbackRouteImport } from './routes/dashboard/payment-callback'
import { Route as DashboardMyAreaRouteImport } from './routes/dashboard/my-area'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardArtisansRouteImport } from './routes/dashboard/artisans'
import { Route as PublicFindRouteImport } from './routes/_public/find'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardWalletCallbackRoute = DashboardWalletCallbackRouteImport.update({
  id: '/wallet-callback',
  path: '/wallet-callback',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPaymentCallbackRoute =
  DashboardPaymentCallbackRouteImport.update({
    id: '/payment-callback',
    path: '/payment-callback',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMyAreaRoute = DashboardMyAreaRouteImport.update({
  id: '/my-area',
  path: '/my-area',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardArtisansRoute = DashboardArtisansRouteImport.update({
  id: '/artisans',
  path: '/artisans',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicFindRoute = PublicFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => PublicRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/find': typeof PublicFindRoute
  '/dashboard/artisans': typeof DashboardArtisansRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-area': typeof DashboardMyAreaRoute
  '/dashboard/payment-callback': typeof DashboardPaymentCallbackRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet-callback': typeof DashboardWalletCallbackRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/find': typeof PublicFindRoute
  '/dashboard/artisans': typeof DashboardArtisansRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-area': typeof DashboardMyAreaRoute
  '/dashboard/payment-callback': typeof DashboardPaymentCallbackRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet-callback': typeof DashboardWalletCallbackRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_public/find': typeof PublicFindRoute
  '/dashboard/artisans': typeof DashboardArtisansRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/my-area': typeof DashboardMyAreaRoute
  '/dashboard/payment-callback': typeof DashboardPaymentCallbackRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/wallet-callback': typeof DashboardWalletCallbackRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/signin'
    | '/signup'
    | '/find'
    | '/dashboard/artisans'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/my-area'
    | '/dashboard/payment-callback'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/wallet-callback'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/find'
    | '/dashboard/artisans'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/my-area'
    | '/dashboard/payment-callback'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/wallet-callback'
    | '/dashboard'
  id:
    | '__root__'
    | '/dashboard'
    | '/_auth'
    | '/_public'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_public/find'
    | '/dashboard/artisans'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/my-area'
    | '/dashboard/payment-callback'
    | '/dashboard/payments'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/wallet-callback'
    | '/_public/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/wallet-callback': {
      id: '/dashboard/wallet-callback'
      path: '/wallet-callback'
      fullPath: '/dashboard/wallet-callback'
      preLoaderRoute: typeof DashboardWalletCallbackRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payment-callback': {
      id: '/dashboard/payment-callback'
      path: '/payment-callback'
      fullPath: '/dashboard/payment-callback'
      preLoaderRoute: typeof DashboardPaymentCallbackRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/my-area': {
      id: '/dashboard/my-area'
      path: '/my-area'
      fullPath: '/dashboard/my-area'
      preLoaderRoute: typeof DashboardMyAreaRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/artisans': {
      id: '/dashboard/artisans'
      path: '/artisans'
      fullPath: '/dashboard/artisans'
      preLoaderRoute: typeof DashboardArtisansRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/find': {
      id: '/_public/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof PublicFindRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardArtisansRoute: typeof DashboardArtisansRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMyAreaRoute: typeof DashboardMyAreaRoute
  DashboardPaymentCallbackRoute: typeof DashboardPaymentCallbackRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWalletCallbackRoute: typeof DashboardWalletCallbackRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardArtisansRoute: DashboardArtisansRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMyAreaRoute: DashboardMyAreaRoute,
  DashboardPaymentCallbackRoute: DashboardPaymentCallbackRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWalletCallbackRoute: DashboardWalletCallbackRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicFindRoute: typeof PublicFindRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFindRoute: PublicFindRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
